# 是否加载内置怪物类型包
load_built_in_packs: true

# 怪物等级范围
level_range:
  min: 1
  max: 95

# 自定义怪物名称
name_prefix: "&7[%sLv.%d&7] "

# 等级相关增益公式
level_curve:
  max_health: "{base} * 0.8 * (pow({e}, 0.0225 * {level}) - 1)"
  attack_damage: "{base} + 1.2 * (pow({e}, 0.0225 * {level}) - 1)"
  knockback_resistance: "{base} + 0.3 * pow({level} / 64, 2)"

# 用于设定怪物等级的公式
level_formula: "{vertical_coeff} * sqrt(abs({y} - 64)) + {horizontal_coeff} * ln(sqrt(pow({x}, 2) + pow({z}, 2)) + 1)"

# 等级增益参数
coeff:
  vertical: 6 # 纵向
  horizontal: 2 # 横向