weightMap:
  - types: [zombie, zombie_villager, husk, drowned, zombified_piglin]
    weights:
      vanilla.zombie: 80
      extend.zombie_strength_cloud: 2
      extend.zombie_totem: 2
      extend.zombie_tnt: 2
      extend.zombie_lava: 2
      extend.zombie_flint_and_steel: 2
      extend.zombie_ender_pearl: 2
      extend.zombie_shield: 2
  - types: [skeleton, stray, wither_skeleton]
    weights:
      vanilla.skeleton: 80
      extend.skeleton_iron_sword: 10
  - types: [spider, cave_spider]
    weights:
      vanilla.spider: 80
  - types: [creeper]
    weights:
      vanilla.creeper: 80