name: EnhancedMobs
main: cn.yanshiqwq.enhanced_mobs.Main
version: 1.0
authors:
  - 'yanshiqwq'
api-version: 1.16
load: STARTUP
description: 一个根据参数定向强化怪物的 Bukkit 插件
folia-supported: true
commands:
  enhancedmobs:
    description: 强化怪物
    usage: /enhancedmobs spawn <怪物类型> <强化类型> <怪物强度> [坐标]